server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plaza
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
user:
  auth:
    service:
      url: http://localhost:8081/api/v1
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
