server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
       name: root
       password: root
user:
  auth:
    service:
      url: ${USERS_SERVICE}

order:
  logs:
    service:
      url: ${TRACEABILITY_SERVICE}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${PHONE_NUMBER}
  messaging-service-sid: ${MESSAGING_SERVICE_SID}

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY:DnkM6Yeq/oVtI4WHmTHqCUSpFZ4eNvPqI7xnsq1upr4=}
      expiration: 86400000
      refresh-token:
        expiration: 604800000

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
